### ISSUE TITLE
No Sync in over a Month

### ISSUE THREAD

**Issue by alpipego** [johnpbloch/wordpress-core#17] opened 2018-11-13 10:45 UTC
It seems the repository hasn't been synced with WordPress in over a month. The last change is from October 11.

#16 is probably connected to this.

**Comment by johnpbloch** [comment] 2018-11-14 05:17
@alpipego Thanks for reporting this. I haven't been able to figure out why this is happening yet, but it's on my radar now and will be fixed as soon as I'm able to determine the cause and the best solution. I appreciate your patience.

**Comment by johnpbloch** [comment] 2018-11-14 17:38
I pushed a new version of the build script to address this and updates are coming in again. I'm going to close this issue, but please let me know if something's amiss. Thanks!

**Closed as completed by johnpbloch** 2018-11-14 17:38 UTC
